export enum GameErrors {
  BAD_REQUEST = 'BAD_REQUEST',
  BAD_MOVE = 'BAD_MOVE',
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  GAME_IS_INACTIVE = 'GAME_IS_INACTIVE',
  USER_ALREADY_IN_GAME = 'USER_ALREADY_IN_GAME'
}